name: event_platform_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.13.6
  dartz: ^0.10.1
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.4
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
